services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - memcached
      - chromedb
    environment:
      - HOTDEAL_ENVIRONMENT=production
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - REDIS_STREAM=streamHotdeals
      - REDIS_STREAM_COUNT=1
      - REDIS_STREAM_MAX_LENGTH=500
      - MEMCACHE_ADDR=memcached:11211
      - CRAWL_INTERVAL_SECONDS=60
      - USE_CHROME_DB=true
      - CHROME_DB_ADDR=http://chromedb:3000
    volumes:
      - ./error:/app/error

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  memcached:
    image: memcached:alpine
    restart: always
    ports:
      - "11211:11211"

  chromedb:
    image: browserless/chrome:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=10
      - ENABLE_CORS=true
      - TOKEN=  # 필요시 설정
    volumes:
      - chrome-data:/tmp

volumes:
  redis-data:
  chrome-data: